### ISSUE TITLE
keeps nagging about the privacy issue

### ISSUE THREAD

**Issue by clarkbw** [clarkbw/searchspot#15]
Got a poor review, need to look into it.

https://addons.mozilla.org/en-US/firefox/addon/awesome-search/reviews/377055/

**Comment by a3overgaauw** [comment]
I really like Awesome Search but every time I restart Firefox I enjoy the Welcome Screen. Thank you for looking into it.
I use the latest Firefox on Windows XP. In a new, empty profile the Welcome Screen is also nagging, so I concluded there is no problem of conflict with other add-ons & also you deliberately constructed it this way.
When I push the button 'Thats fine, lets try this!' the screen disappears. I am unsure about 'Preferences' in the Welcome Screen. Do you mean anything other than the 'Search Preferences...'?
If you need any other information, I am glad to provide.

**Comment by clarkbw** [comment]
Yes, the welcome panel is required for anyone on their first use of the add-on.  However it is supposed to save your (yes) response in your preferences such that it doesn't ask you every time you restart Firefox.  So installing the add-on in a new profile should prompt you the first time but then never again after you select yes.

With this new profile is the add-on continually prompting you again?

In your existing profile you can do this.  Go to the `about:config` page by typing `about:config` into the URL bar of Firefox.  Then in the search field paste in the following: `extensions.jid1-wB2HoBahvZDBDQ.allowStatisticsReporting` which should narrow down the results of your preferences to the one related to that panel dialog.  This preference should be set to `true` and the status should be set to `user set`.  If it's not set then I can take a look at that code otherwise it's likely something else going on.

Thanks!

**Comment by a3overgaauw** [comment]
In about:config I dit not found extensions.jid1-wB2HoBahvZDBDQ.allowStatisticsReporting.
But instead I found extensions.jid1-wB2HoBahvZDBDQ@jetpack.allowStatisticsReporting and it was filled this way: user set, boolean, true.
Probably it is not a bright idea, but this weekend I plan to reinstall Firefox 15.0 completely.

**Comment by clarkbw** [comment]
I haven't been able to track down the problem anywhere.  It does seem strange that you have a different preference value than I do and I'm hoping the reinstall fixed something.  Closing this for now.
