### ISSUE TITLE
Disabling the addon hides all chrome

### ISSUE THREAD

**Issue by erikvold** [clarkbw/searchspot#45]
I was using 1.0.2, opened a new window and tried to change my search provider from google to bugzilla which I couldn't do, so I disabled the add-on, then all chrome for all tabs was hidden in the new window only.

**Comment by clarkbw** [comment]
Yeah, version 1.0.2 was using the original addon-page module so it should be giving you the dead object error as well.  If you can, upgrade to 1.1.0 but it's still awaiting preliminary review.  I'm in position 90 of 140 for review right now, assuming I don't get rejected again that new version should carry the new addon-page changes.

We can reopen this if you see the problem with the latest version.

**Comment by erikvold** [comment]
It looks like 1.10 was built on the sdk's master branch, if you repack on SDK 1.14 then I can do the review.

**Comment by clarkbw** [comment]
Ok, I'm taking you up on that offer!  Repacked a 1.1.1 version on the 1.14 release of the SDK.

**Comment by erikvold** [comment]
So it looks like the version of jQuery packed with this add-on is unrecognized by the validator, I'm told a push on Thursday will include some 1.10 checksums so I will have to wait until then to review, otherwise I'd have to reject it.

Also I gave you some bad advice it turns out (sorry bro!), in the future use `cfx xpi --strip-sdk` (on master branch is fine) until we (Jetpack team) gets our act together and make this the default..

**Comment by erikvold** [comment]
Ah Kris already checked those checksums with a script.
